version: '3.8'

services:
  trailbase:
    image: trailbase/trailbase:latest
    ports:
      - "4000:4000"
    volumes:
      - ./traildepot:/app/traildepot
    environment:
      - TB_ADMIN_EMAIL=admin@example.com
      - TB_ADMIN_PASSWORD=admin123
      - TB_CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173